name: "Parse Nix"

on:
  push:
    paths-ignore:
      - '*/*.md'
      - '*/*.org'
  pull_request:
    paths-ignore:
      - '*/*.md'
      - '*/*.org'

jobs:
  parse:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./nixos
    steps:
    - name: "Check out code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: "Install Nix"
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: "Check flake"
      run: nix flake check --no-build
